import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadSummarizeConfig, type SummarizeConfig } from "../config.js";
import {
  createResearchMemoryStoreFromConfig,
  type ResearchMemoryStoreFactoryResult,
} from "../research-memory/factory.js";
import type {
  ResearchMemoryArtifact,
  ResearchMemoryJsonObject,
  ResearchMemoryJsonValue,
  ResearchMemoryListRunsOptions,
  ResearchMemoryRun,
  ResearchMemoryRunKind,
  ResearchMemoryRunSnapshot,
  ResearchMemoryRunStatus,
  ResearchMemoryStore,
} from "../research-memory/store.js";
import {
  RESEARCH_MEMORY_RUN_KINDS,
  RESEARCH_MEMORY_RUN_STATUSES,
} from "../research-memory/store.js";
import { buildMemoryHelp } from "./help.js";

type MemoryCliContext = {
  normalizedArgv: string[];
  envForRun: Record<string, string | undefined>;
  stdout: NodeJS.WritableStream;
  setExitCode?: (code: number) => void;
};

export type MemoryCliDeps = {
  loadConfig?: typeof loadSummarizeConfig;
  createStoreFromConfig?: typeof createResearchMemoryStoreFromConfig;
  cwd?: () => string;
  readFile?: typeof readFile;
  mkdir?: typeof mkdir;
  writeFile?: typeof writeFile;
};

type MemoryStoreState = {
  config: SummarizeConfig | null;
  configPath: string | null;
  result: ResearchMemoryStoreFactoryResult;
};

type MemoryListOptions = {
  json: boolean;
  limit: number;
  order: "asc" | "desc";
  status: ResearchMemoryRunStatus | null;
  kind: ResearchMemoryRunKind | null;
};

type MemoryShowOptions = {
  json: boolean;
  runId: string;
};

type MemoryExportOptions = {
  json: boolean;
  runId: string;
  output: string | null;
  language: ExportLanguage | "auto";
};

export type ExportLanguage = "en" | "zh-TW";

type ExportLabels = {
  title: string;
  generatedBy: string;
  runMetadata: string;
  privacyMode: string;
  sources: string;
  summary: string;
  sourceText: string;
  transcripts: string;
  slides: string;
  routeMetadata: string;
  events: string;
  failures: string;
  notebookExports: string;
  missing: string;
};

const EN_LABELS: ExportLabels = {
  title: "NotebookLM Source Bundle",
  generatedBy: "Generated by summarize memory export.",
  runMetadata: "Run Metadata",
  privacyMode: "Privacy Mode",
  sources: "Sources",
  summary: "Summary",
  sourceText: "Source Text",
  transcripts: "Transcripts",
  slides: "Slides",
  routeMetadata: "Route Metadata",
  events: "Events",
  failures: "Failures",
  notebookExports: "Notebook Exports",
  missing: "Not available",
};

const ZH_TW_LABELS: ExportLabels = {
  title: "NotebookLM 來源匯出包",
  generatedBy: "由 summarize memory export 產生。",
  runMetadata: "執行中繼資料",
  privacyMode: "隱私模式",
  sources: "來源",
  summary: "摘要",
  sourceText: "來源文字",
  transcripts: "逐字稿",
  slides: "投影片",
  routeMetadata: "路由中繼資料",
  events: "事件",
  failures: "失敗紀錄",
  notebookExports: "Notebook 匯出紀錄",
  missing: "無可用資料",
};

const JSON_BLOCK = "```json";

function hasArg(argv: readonly string[], name: string): boolean {
  return argv.includes(name) || argv.some((arg) => arg.startsWith(`${name}=`));
}

function wantsHelp(argv: readonly string[]): boolean {
  return argv.includes("--help") || argv.includes("-h") || argv.includes("help");
}

function readArgValue(argv: readonly string[], names: readonly string[]): string | null {
  for (const name of names) {
    const eq = argv.find((arg) => arg.startsWith(`${name}=`));
    if (eq) {
      const value = eq.slice(`${name}=`.length).trim();
      if (!value) throw new Error(`Missing value for ${name}`);
      return value;
    }
    const index = argv.indexOf(name);
    if (index === -1) continue;
    const next = argv[index + 1];
    if (!next || next.startsWith("-")) throw new Error(`Missing value for ${name}`);
    return next.trim();
  }
  return null;
}

function parsePositionals(argv: readonly string[], valueOptions: readonly string[]): string[] {
  const out: string[] = [];
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg) continue;
    if (arg.startsWith("--")) {
      const name = arg.includes("=") ? arg.slice(0, arg.indexOf("=")) : arg;
      if (valueOptions.includes(name) && !arg.includes("=")) index += 1;
      continue;
    }
    if (arg.startsWith("-")) {
      if (valueOptions.includes(arg)) index += 1;
      continue;
    }
    if (arg !== "help") out.push(arg);
  }
  return out;
}

function parsePositiveInteger(raw: string | null, fallback: number, label: string): number {
  if (!raw) return fallback;
  const parsed = Number(raw);
  if (!Number.isInteger(parsed) || parsed < 1) {
    throw new Error(`${label} must be a positive integer`);
  }
  return parsed;
}

function parseStatus(raw: string | null): ResearchMemoryRunStatus | null {
  if (!raw) return null;
  if ((RESEARCH_MEMORY_RUN_STATUSES as readonly string[]).includes(raw)) {
    return raw as ResearchMemoryRunStatus;
  }
  throw new Error(
    `--status must be one of ${RESEARCH_MEMORY_RUN_STATUSES.map((status) => `"${status}"`).join(", ")}`,
  );
}

function parseKind(raw: string | null): ResearchMemoryRunKind | null {
  if (!raw) return null;
  if ((RESEARCH_MEMORY_RUN_KINDS as readonly string[]).includes(raw)) {
    return raw as ResearchMemoryRunKind;
  }
  throw new Error(
    `--kind must be one of ${RESEARCH_MEMORY_RUN_KINDS.map((kind) => `"${kind}"`).join(", ")}`,
  );
}

function parseOrder(raw: string | null): "asc" | "desc" {
  if (!raw) return "desc";
  if (raw === "asc" || raw === "desc") return raw;
  throw new Error('--order must be "asc" or "desc"');
}

export function parseExportLanguage(
  raw: string | null,
  traditionalChinese: boolean,
): ExportLanguage | "auto" {
  if (traditionalChinese) return "zh-TW";
  if (!raw) return "auto";
  const normalized = raw.trim().toLowerCase();
  if (!normalized || normalized === "auto") return "auto";
  if (
    normalized === "zh-tw" ||
    normalized === "zh_hant" ||
    normalized === "zh-hant" ||
    normalized === "traditional" ||
    normalized === "traditional-chinese" ||
    normalized === "tc"
  ) {
    return "zh-TW";
  }
  if (normalized === "en" || normalized === "english") return "en";
  throw new Error('--language must be "auto", "en", "english", "zh-TW", or "traditional-chinese"');
}

function parseListOptions(argv: readonly string[]): MemoryListOptions {
  const args = argv.slice(2);
  const positionals = parsePositionals(args, ["--limit", "--status", "--kind", "--order"]);
  if (positionals.length > 0) {
    throw new Error(`Unexpected memory list argument: ${positionals[0]}`);
  }
  return {
    json: hasArg(args, "--json"),
    limit: parsePositiveInteger(readArgValue(args, ["--limit"]), 20, "--limit"),
    order: parseOrder(readArgValue(args, ["--order"])),
    status: parseStatus(readArgValue(args, ["--status"])),
    kind: parseKind(readArgValue(args, ["--kind"])),
  };
}

function parseShowOptions(argv: readonly string[]): MemoryShowOptions {
  const args = argv.slice(2);
  const positionals = parsePositionals(args, []);
  if (positionals.length !== 1) {
    throw new Error("Usage: summarize memory show <run-id> [--json]");
  }
  return {
    json: hasArg(args, "--json"),
    runId: positionals[0] ?? "",
  };
}

function parseExportOptions(argv: readonly string[]): MemoryExportOptions {
  const args = argv.slice(2);
  const positionals = parsePositionals(args, ["--output", "-o", "--language", "--lang"]);
  if (positionals.length !== 1) {
    throw new Error("Usage: summarize memory export <run-id> [--output <path>] [--language zh-TW]");
  }
  return {
    json: hasArg(args, "--json"),
    runId: positionals[0] ?? "",
    output: readArgValue(args, ["--output", "-o"]),
    language: parseExportLanguage(
      readArgValue(args, ["--language", "--lang"]),
      hasArg(args, "--traditional-chinese") || hasArg(args, "--zh-tw"),
    ),
  };
}

function resolveStoreState(
  envForRun: Record<string, string | undefined>,
  deps: MemoryCliDeps,
): MemoryStoreState {
  const loadConfig = deps.loadConfig ?? loadSummarizeConfig;
  const createStoreFromConfig = deps.createStoreFromConfig ?? createResearchMemoryStoreFromConfig;
  const { config, path: configPath } = loadConfig({ env: envForRun });
  return {
    config,
    configPath,
    result: createStoreFromConfig({ config, env: envForRun }),
  };
}

async function withResearchMemoryStore<T>(
  state: MemoryStoreState,
  operation: (store: ResearchMemoryStore, artifactRoot: string) => Promise<T>,
): Promise<T> {
  const { result } = state;
  if (!result.store || !result.artifactRoot) {
    throw new Error(formatUnavailableMemoryStore(result));
  }
  await result.store.initialize();
  try {
    return await operation(result.store, result.artifactRoot);
  } finally {
    await result.store.close();
  }
}

export function formatUnavailableMemoryStore(result: ResearchMemoryStoreFactoryResult): string {
  if (result.kind === "disabled") {
    return result.reason === "not-configured"
      ? "Research memory is not configured. Set researchMemory.enabled=true with a backend before using memory commands."
      : "Research memory is disabled by config.";
  }
  if (result.kind === "sqlite-placeholder") {
    return "SQLite research memory is not implemented yet. Use backend=postgres or backend=memory.";
  }
  return "Research memory store is unavailable.";
}

function formatDate(ms: number | null): string {
  return typeof ms === "number" && Number.isFinite(ms) ? new Date(ms).toISOString() : "n/a";
}

function truncate(value: string | null | undefined, max = 80): string {
  const text = value?.replace(/\s+/g, " ").trim() ?? "";
  if (text.length <= max) return text || "-";
  return `${text.slice(0, max - 1)}...`;
}

function jsonBlock(value: unknown): string {
  return `${JSON_BLOCK}\n${JSON.stringify(value, null, 2)}\n\`\`\``;
}

function jsonObjectHasKeys(value: ResearchMemoryJsonObject | null | undefined): boolean {
  return Boolean(value && Object.keys(value).length > 0);
}

function markdownValue(value: string | number | boolean | null | undefined): string {
  if (value === null || typeof value === "undefined" || value === "") return "n/a";
  return String(value);
}

function listOptionsToStoreOptions(options: MemoryListOptions): ResearchMemoryListRunsOptions {
  return {
    order: options.order,
    limit: options.limit,
    ...(options.status ? { status: options.status } : {}),
    ...(options.kind ? { kind: options.kind } : {}),
  };
}

function writeRunList(stdout: NodeJS.WritableStream, runs: readonly ResearchMemoryRun[]): void {
  if (runs.length === 0) {
    stdout.write("No research memory runs found.\n");
    return;
  }
  stdout.write(["ID", "STATUS", "KIND", "MODE", "CREATED", "INPUT"].join("\t"));
  stdout.write("\n");
  for (const run of runs) {
    stdout.write(
      [
        run.id,
        run.status,
        run.kind,
        run.mode,
        formatDate(run.createdAt),
        truncate(run.inputRef, 100),
      ].join("\t"),
    );
    stdout.write("\n");
  }
}

function findSummaryArtifact(snapshot: ResearchMemoryRunSnapshot): ResearchMemoryArtifact | null {
  if (snapshot.run.summaryArtifactId) {
    const artifact = snapshot.artifacts.find(
      (candidate) => candidate.id === snapshot.run.summaryArtifactId,
    );
    if (artifact) return artifact;
  }
  return snapshot.artifacts.find((artifact) => artifact.artifactKind === "summary") ?? null;
}

function isTextualArtifact(artifact: ResearchMemoryArtifact): boolean {
  return (
    artifact.artifactKind === "extracted-text" ||
    artifact.artifactKind === "transcript" ||
    artifact.artifactKind === "summary" ||
    artifact.artifactKind === "ocr-text" ||
    artifact.artifactKind === "user-note"
  );
}

function isSlidesJsonArtifact(artifact: ResearchMemoryArtifact): boolean {
  return artifact.artifactKind === "slides-json";
}

function resolveArtifactPath(artifactRoot: string, relativePath: string): string {
  const base = path.resolve(artifactRoot);
  const full = path.resolve(base, relativePath);
  const relative = path.relative(base, full);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Research memory artifact path escapes artifact root: ${relativePath}`);
  }
  return full;
}

async function readArtifactText(
  artifact: ResearchMemoryArtifact,
  artifactRoot: string,
  deps: MemoryCliDeps,
): Promise<string | null> {
  if (artifact.storageKind === "inline-text") return artifact.inlineText;
  if (artifact.storageKind === "inline-json") return JSON.stringify(artifact.inlineJson, null, 2);
  if (artifact.storageKind === "file") {
    const filePath = resolveArtifactPath(artifactRoot, artifact.relativePath);
    return await (deps.readFile ?? readFile)(filePath, "utf8");
  }
  return null;
}

function formatShowSnapshot(snapshot: ResearchMemoryRunSnapshot): string {
  const lines: string[] = [];
  lines.push(`Run ${snapshot.run.id}`);
  lines.push(`  Status: ${snapshot.run.status}`);
  lines.push(`  Kind/mode: ${snapshot.run.kind}/${snapshot.run.mode}`);
  lines.push(`  Created: ${formatDate(snapshot.run.createdAt)}`);
  lines.push(`  Completed: ${formatDate(snapshot.run.completedAt)}`);
  lines.push(`  Input: ${markdownValue(snapshot.run.inputRef)}`);
  lines.push(
    `  Language: ${markdownValue(snapshot.run.languageRaw)} (${snapshot.run.languageBucket ?? "n/a"})`,
  );
  lines.push(`  Summary artifact: ${snapshot.run.summaryArtifactId ?? "n/a"}`);
  lines.push("");
  lines.push(`Sources (${snapshot.sources.length})`);
  for (const source of snapshot.sources) {
    lines.push(
      `  - ${source.id}: ${source.sourceKind} ${source.title ? `"${source.title}" ` : ""}${source.canonicalUrl ?? ""}`.trimEnd(),
    );
  }
  lines.push("");
  lines.push(`Artifacts (${snapshot.artifacts.length})`);
  for (const artifact of snapshot.artifacts) {
    lines.push(
      `  - ${artifact.id}: ${artifact.artifactKind} ${artifact.storageKind} ${artifact.byteSize ?? "unknown"} bytes`,
    );
  }
  lines.push("");
  lines.push(`Routes (${snapshot.modelRoutes.length})`);
  for (const route of snapshot.modelRoutes) {
    lines.push(
      `  - attempt ${route.attemptIndex}: ${route.selectedModelId ?? "n/a"} via ${route.selectionSource} localOnly=${route.localOnlyAllowed}`,
    );
  }
  if (snapshot.failures.length > 0) {
    lines.push("");
    lines.push(`Failures (${snapshot.failures.length})`);
    for (const failure of snapshot.failures) {
      lines.push(`  - ${failure.failureStage}: ${failure.message}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function selectExportLanguage(
  requested: ExportLanguage | "auto",
  snapshot: ResearchMemoryRunSnapshot,
): ExportLanguage {
  if (requested !== "auto") return requested;
  return snapshot.run.languageBucket === "traditionalChinese" ||
    snapshot.run.languageBucket === "bilingual"
    ? "zh-TW"
    : "en";
}

function labelsFor(language: ExportLanguage): ExportLabels {
  return language === "zh-TW" ? ZH_TW_LABELS : EN_LABELS;
}

function artifactCitationLine(artifact: ResearchMemoryArtifact): string | null {
  const citations = artifact.metadata.citations;
  if (typeof citations === "number" || typeof citations === "string") {
    return `- Citations: ${citations}`;
  }
  if (Array.isArray(citations) && citations.length > 0) {
    return `- Citations: ${citations.map((item) => String(item)).join(", ")}`;
  }
  return null;
}

function formatSeconds(seconds: number): string {
  const clamped = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(clamped / 3600);
  const minutes = Math.floor((clamped % 3600) / 60);
  const secs = clamped % 60;
  const mm = String(minutes).padStart(2, "0");
  const ss = String(secs).padStart(2, "0");
  if (hours <= 0) return `${minutes}:${ss}`;
  return `${String(hours).padStart(2, "0")}:${mm}:${ss}`;
}

function slideLinesFromJson(value: ResearchMemoryJsonValue): string[] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return [];
  const slides = (value as Record<string, unknown>).slides;
  if (!Array.isArray(slides)) return [];
  const lines: string[] = [];
  for (const slide of slides) {
    if (!slide || typeof slide !== "object") continue;
    const entry = slide as Record<string, unknown>;
    const index = typeof entry.index === "number" ? entry.index : lines.length + 1;
    const timestamp =
      typeof entry.timestamp === "number" && Number.isFinite(entry.timestamp)
        ? formatSeconds(entry.timestamp)
        : "n/a";
    const imagePath =
      typeof entry.imagePath === "string" && entry.imagePath.trim() ? entry.imagePath.trim() : null;
    const ocrText = typeof entry.ocrText === "string" ? entry.ocrText.trim() : "";
    lines.push(`### Slide ${index} [${timestamp}]`);
    if (imagePath) lines.push(`- Image: ${imagePath}`);
    if (ocrText) {
      lines.push("");
      lines.push(ocrText);
    }
    lines.push("");
  }
  return lines;
}

export async function buildNotebookLmMarkdownBundle({
  snapshot,
  artifactRoot,
  language,
  deps,
}: {
  snapshot: ResearchMemoryRunSnapshot;
  artifactRoot: string;
  language: ExportLanguage;
  deps: MemoryCliDeps;
}): Promise<string> {
  const labels = labelsFor(language);
  const lines: string[] = [];
  const sourceTitle =
    snapshot.sources.find((source) => source.title)?.title ??
    snapshot.run.inputRef ??
    snapshot.run.id;
  const summaryArtifact = findSummaryArtifact(snapshot);
  const summaryText = summaryArtifact
    ? await readArtifactText(summaryArtifact, artifactRoot, deps)
    : null;
  const sourceArtifacts = snapshot.artifacts.filter(
    (artifact) =>
      artifact.id !== summaryArtifact?.id &&
      (artifact.artifactKind === "extracted-text" || artifact.artifactKind === "ocr-text"),
  );
  const transcriptArtifacts = snapshot.artifacts.filter(
    (artifact) => artifact.id !== summaryArtifact?.id && artifact.artifactKind === "transcript",
  );
  const slideArtifacts = snapshot.artifacts.filter(isSlidesJsonArtifact);

  lines.push(`# ${labels.title}: ${sourceTitle}`);
  lines.push("");
  lines.push(labels.generatedBy);
  lines.push("");
  lines.push(`## ${labels.runMetadata}`);
  lines.push("");
  lines.push(`- Run ID: ${snapshot.run.id}`);
  lines.push(`- Status: ${snapshot.run.status}`);
  lines.push(`- Kind: ${snapshot.run.kind}`);
  lines.push(`- Mode: ${snapshot.run.mode}`);
  lines.push(`- Created: ${formatDate(snapshot.run.createdAt)}`);
  lines.push(`- Started: ${formatDate(snapshot.run.startedAt)}`);
  lines.push(`- Completed: ${formatDate(snapshot.run.completedAt)}`);
  lines.push(`- Input: ${markdownValue(snapshot.run.inputRef)}`);
  lines.push(`- Length: ${markdownValue(snapshot.run.length)}`);
  lines.push(
    `- Language: ${markdownValue(snapshot.run.languageRaw)} (${snapshot.run.languageBucket ?? "n/a"})`,
  );
  lines.push(`- Requested format: ${markdownValue(snapshot.run.requestedFormat)}`);
  lines.push("");
  lines.push(`## ${labels.privacyMode}`);
  lines.push("");
  lines.push(`- Local only: ${snapshot.run.privacyMode.localOnlyEnabled ? "yes" : "no"}`);
  lines.push(`- Local only source: ${markdownValue(snapshot.run.privacyMode.localOnlySource)}`);
  lines.push(`- Policy result: ${snapshot.run.privacyMode.policyResult}`);
  lines.push(
    `- Allowed transports: ${snapshot.run.privacyMode.allowedTransports.join(", ") || "none"}`,
  );
  lines.push(`- Protected data: ${snapshot.run.privacyMode.protectedData.join(", ") || "none"}`);
  lines.push(`- Export state: ${snapshot.run.privacyMode.exportState}`);
  lines.push(`- Notes: ${markdownValue(snapshot.run.privacyMode.notes)}`);
  if (jsonObjectHasKeys(snapshot.run.privacyMode.metadata)) {
    lines.push("");
    lines.push(jsonBlock(snapshot.run.privacyMode.metadata));
  }
  lines.push("");
  lines.push(`## ${labels.sources}`);
  lines.push("");
  if (snapshot.sources.length === 0) {
    lines.push(labels.missing);
  }
  for (const [index, source] of snapshot.sources.entries()) {
    const title = source.title ?? source.canonicalUrl ?? source.id;
    lines.push(`### ${index + 1}. ${title}`);
    lines.push("");
    lines.push(`- Source ID: ${source.id}`);
    lines.push(`- Kind: ${source.sourceKind}`);
    lines.push(`- URL: ${markdownValue(source.canonicalUrl)}`);
    lines.push(`- Site: ${markdownValue(source.siteName)}`);
    lines.push(`- Content type: ${markdownValue(source.contentType)}`);
    lines.push(`- Language hint: ${markdownValue(source.languageHint)}`);
    lines.push(`- Created: ${formatDate(source.createdAt)}`);
    if (jsonObjectHasKeys(source.fetchMetadata)) {
      lines.push("");
      lines.push(jsonBlock(source.fetchMetadata));
    }
    lines.push("");
  }
  lines.push(`## ${labels.summary}`);
  lines.push("");
  if (summaryText?.trim()) {
    const citations = summaryArtifact ? artifactCitationLine(summaryArtifact) : null;
    if (citations) {
      lines.push(citations);
      lines.push("");
    }
    lines.push(summaryText.trim());
  } else {
    lines.push(labels.missing);
  }
  if (sourceArtifacts.length > 0) {
    lines.push("");
    lines.push(`## ${labels.sourceText}`);
    for (const artifact of sourceArtifacts) {
      const text = isTextualArtifact(artifact)
        ? await readArtifactText(artifact, artifactRoot, deps)
        : null;
      if (!text?.trim()) continue;
      const source = artifact.sourceId
        ? snapshot.sources.find((candidate) => candidate.id === artifact.sourceId)
        : null;
      lines.push("");
      lines.push(`### ${source?.title ?? source?.canonicalUrl ?? artifact.id}`);
      const citations = artifactCitationLine(artifact);
      if (citations) lines.push(citations);
      lines.push("");
      lines.push(text.trim());
    }
  }
  if (transcriptArtifacts.length > 0) {
    lines.push("");
    lines.push(`## ${labels.transcripts}`);
    for (const artifact of transcriptArtifacts) {
      const text = await readArtifactText(artifact, artifactRoot, deps);
      if (!text?.trim()) continue;
      const source = artifact.sourceId
        ? snapshot.sources.find((candidate) => candidate.id === artifact.sourceId)
        : null;
      lines.push("");
      lines.push(`### ${source?.title ?? source?.canonicalUrl ?? artifact.id}`);
      const citations = artifactCitationLine(artifact);
      if (citations) lines.push(citations);
      lines.push("");
      lines.push(text.trim());
    }
  }
  if (slideArtifacts.length > 0) {
    lines.push("");
    lines.push(`## ${labels.slides}`);
    for (const artifact of slideArtifacts) {
      lines.push("");
      if (artifact.storageKind === "inline-json") {
        const slideLines = slideLinesFromJson(artifact.inlineJson);
        if (slideLines.length > 0) {
          lines.push(...slideLines);
          continue;
        }
      }
      const text = await readArtifactText(artifact, artifactRoot, deps);
      lines.push(text?.trim() ? jsonBlock(JSON.parse(text)) : labels.missing);
    }
  }
  if (snapshot.modelRoutes.length > 0) {
    lines.push("");
    lines.push(`## ${labels.routeMetadata}`);
    for (const route of snapshot.modelRoutes) {
      lines.push("");
      lines.push(`### Attempt ${route.attemptIndex}`);
      lines.push("");
      lines.push(`- Requested model: ${markdownValue(route.requestedModelInput)}`);
      lines.push(`- Selected model: ${markdownValue(route.selectedModelId)}`);
      lines.push(`- Selection source: ${route.selectionSource}`);
      lines.push(`- Language bucket: ${route.languageBucket}`);
      lines.push(`- Provider: ${markdownValue(route.providerKind)}`);
      lines.push(`- Local runtime: ${markdownValue(route.localRuntimeKind)}`);
      lines.push(`- Endpoint host: ${markdownValue(route.endpointHost)}`);
      lines.push(`- Probe status: ${route.probeStatus}`);
      lines.push(`- Local only allowed: ${route.localOnlyAllowed ? "yes" : "no"}`);
      lines.push(`- Blocked reason: ${markdownValue(route.blockedReason)}`);
      if (jsonObjectHasKeys(route.metadata)) {
        lines.push("");
        lines.push(jsonBlock(route.metadata));
      }
    }
  }
  if (snapshot.events.length > 0) {
    lines.push("");
    lines.push(`## ${labels.events}`);
    for (const event of snapshot.events.filter((candidate) => candidate.visibleToUi)) {
      lines.push(
        `- ${formatDate(event.createdAt)} ${event.eventType}: ${JSON.stringify(event.payload)}`,
      );
    }
  }
  if (snapshot.failures.length > 0) {
    lines.push("");
    lines.push(`## ${labels.failures}`);
    for (const failure of snapshot.failures) {
      lines.push(`- ${formatDate(failure.createdAt)} ${failure.failureStage}: ${failure.message}`);
    }
  }
  if (snapshot.notebookExports.length > 0) {
    lines.push("");
    lines.push(`## ${labels.notebookExports}`);
    for (const notebookExport of snapshot.notebookExports) {
      lines.push(
        `- ${formatDate(notebookExport.createdAt)} ${notebookExport.provider}/${notebookExport.status}: ${notebookExport.notebookTitle ?? notebookExport.notebookId ?? "n/a"}`,
      );
    }
  }
  return `${lines
    .join("\n")
    .replace(/\n{4,}/g, "\n\n\n")
    .trim()}\n`;
}

async function handleStatus({
  state,
  stdout,
  json,
  setExitCode,
}: {
  state: MemoryStoreState;
  stdout: NodeJS.WritableStream;
  json: boolean;
  setExitCode?: (code: number) => void;
}): Promise<void> {
  const basePayload = {
    configured: Boolean(state.config?.researchMemory),
    configPath: state.configPath,
    kind: state.result.kind,
    backend: state.result.backend,
    artifactRoot: state.result.artifactRoot,
    reason: state.result.reason,
  };
  if (!state.result.store || !state.result.artifactRoot) {
    if (json) {
      stdout.write(`${JSON.stringify({ ...basePayload, available: false }, null, 2)}\n`);
      return;
    }
    stdout.write("Research memory status\n");
    stdout.write(`  Configured: ${basePayload.configured ? "yes" : "no"}\n`);
    stdout.write(`  Backend: ${basePayload.backend ?? "none"}\n`);
    stdout.write(`  Available: no (${basePayload.reason ?? "unavailable"})\n`);
    if (basePayload.artifactRoot) stdout.write(`  Artifact root: ${basePayload.artifactRoot}\n`);
    return;
  }
  try {
    await withResearchMemoryStore(state, async (store) => {
      const recentRuns = await store.listRuns({ limit: 5, order: "desc" });
      if (json) {
        stdout.write(
          `${JSON.stringify({ ...basePayload, available: true, recentRuns }, null, 2)}\n`,
        );
        return;
      }
      stdout.write("Research memory status\n");
      stdout.write(`  Configured: ${basePayload.configured ? "yes" : "no"}\n`);
      stdout.write(`  Backend: ${basePayload.backend}\n`);
      stdout.write("  Available: yes\n");
      stdout.write(`  Artifact root: ${basePayload.artifactRoot}\n`);
      stdout.write(`  Recent runs: ${recentRuns.length}\n`);
    });
  } catch (error) {
    if (json) {
      stdout.write(
        `${JSON.stringify(
          {
            ...basePayload,
            available: false,
            error: error instanceof Error ? error.message : String(error),
          },
          null,
          2,
        )}\n`,
      );
    } else {
      stdout.write("Research memory status\n");
      stdout.write(`  Configured: ${basePayload.configured ? "yes" : "no"}\n`);
      stdout.write(`  Backend: ${basePayload.backend ?? "none"}\n`);
      stdout.write(`  Available: no (${error instanceof Error ? error.message : String(error)})\n`);
    }
    setExitCode?.(1);
  }
}

export async function handleMemoryCliRequest(
  { normalizedArgv, envForRun, stdout, setExitCode }: MemoryCliContext,
  deps: MemoryCliDeps = {},
): Promise<boolean> {
  if (normalizedArgv[0]?.toLowerCase() !== "memory") return false;

  const subcommand = normalizedArgv[1]?.toLowerCase() ?? "status";
  if (wantsHelp(normalizedArgv)) {
    stdout.write(`${buildMemoryHelp()}\n`);
    return true;
  }

  const state = resolveStoreState(envForRun, deps);
  if (subcommand === "status") {
    await handleStatus({
      state,
      stdout,
      json: hasArg(normalizedArgv.slice(2), "--json"),
      setExitCode,
    });
    return true;
  }

  if (subcommand === "list") {
    const options = parseListOptions(normalizedArgv);
    await withResearchMemoryStore(state, async (store) => {
      const runs = await store.listRuns(listOptionsToStoreOptions(options));
      if (options.json) {
        stdout.write(`${JSON.stringify({ runs }, null, 2)}\n`);
      } else {
        writeRunList(stdout, runs);
      }
    });
    return true;
  }

  if (subcommand === "show") {
    const options = parseShowOptions(normalizedArgv);
    await withResearchMemoryStore(state, async (store) => {
      const snapshot = await store.getRun(options.runId);
      if (!snapshot) throw new Error(`Research memory run not found: ${options.runId}`);
      stdout.write(
        options.json ? `${JSON.stringify(snapshot, null, 2)}\n` : formatShowSnapshot(snapshot),
      );
    });
    return true;
  }

  if (subcommand === "export") {
    const options = parseExportOptions(normalizedArgv);
    await withResearchMemoryStore(state, async (store, artifactRoot) => {
      const snapshot = await store.getRun(options.runId);
      if (!snapshot) throw new Error(`Research memory run not found: ${options.runId}`);
      const language = selectExportLanguage(options.language, snapshot);
      const markdown = await buildNotebookLmMarkdownBundle({
        snapshot,
        artifactRoot,
        language,
        deps,
      });
      if (!options.output) {
        if (options.json) {
          stdout.write(
            `${JSON.stringify({ runId: options.runId, language, markdown }, null, 2)}\n`,
          );
        } else {
          stdout.write(markdown);
        }
        return;
      }
      const cwd = deps.cwd?.() ?? process.cwd();
      const outputPath = path.resolve(cwd, options.output);
      await (deps.mkdir ?? mkdir)(path.dirname(outputPath), { recursive: true });
      await (deps.writeFile ?? writeFile)(outputPath, markdown, "utf8");
      const payload = {
        runId: options.runId,
        language,
        path: outputPath,
        bytes: Buffer.byteLength(markdown, "utf8"),
      };
      if (options.json) {
        stdout.write(`${JSON.stringify(payload, null, 2)}\n`);
      } else {
        stdout.write(`Exported research memory bundle: ${outputPath}\n`);
      }
    });
    return true;
  }

  stdout.write(`${buildMemoryHelp()}\n`);
  return true;
}
